name: security-scan
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        shell: bash
        run: |
          set -euxo pipefail

          # Syft + Grype
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh  | sh -s -- -b /usr/local/bin
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

          # Python deps
          python3 -m pip install --upgrade pip
          python3 -m pip install jinja2 bandit semgrep

          # Gitleaks — install from release tarball (reliable)
          curl -sSfL \
            https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks_Linux_x86_64.tar.gz \
            -o /tmp/gitleaks.tar.gz
          mkdir -p "$HOME/.local/bin"
          tar -xzf /tmp/gitleaks.tar.gz -C "$HOME/.local/bin" gitleaks
          chmod +x "$HOME/.local/bin/gitleaks"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

          # Trivy
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
            | sh -s -- -b /usr/local/bin

          # HTML → PDF
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf

      - name: Run scans and build report
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force run_artifacts | Out-Null

          # SBOM + Grype (script in repo)
          ./run_all.ps1 -RepoPath ./ -VenvSite ""

          # Extra analyzers (don't fail the job on non-zero tool exit)
          if (Get-Command semgrep -ErrorAction SilentlyContinue) {
            & semgrep --config auto --json --output run_artifacts/semgrep.json . ; if ($LASTEXITCODE -ne 0) { $LASTEXITCODE = 0 }
          }
          if (Get-Command bandit -ErrorAction SilentlyContinue) {
            & bandit -r . -f json -o run_artifacts/bandit.json ; if ($LASTEXITCODE -ne 0) { $LASTEXITCODE = 0 }
          }
          if (Get-Command gitleaks -ErrorAction SilentlyContinue) {
            & gitleaks detect --source . -f json -r run_artifacts/gitleaks.json ; if ($LASTEXITCODE -ne 0) { $LASTEXITCODE = 0 }
          }
          if (Get-Command trivy -ErrorAction SilentlyContinue) {
            & trivy config --format json --output run_artifacts/trivy_config.json . ; if ($LASTEXITCODE -ne 0) { $LASTEXITCODE = 0 }
          }

          # Build HTML from repo script, then PDF
          python3 make_report.py
          wkhtmltopdf run_artifacts/report.html run_artifacts/report.pdf

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: run_artifacts/*
