name: security-scan
on: [push, pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
          python3 -m pip install --upgrade pip
          python3 -m pip install bandit semgrep
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64.tar.gz \
            | tar -xz -C /usr/local/bin gitleaks
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
          sudo apt-get update && sudo apt-get install -y chromium-browser

      - name: Run scans
        shell: pwsh
        run: |
          ./run_all.ps1 -RepoPath ./ -VenvSite ""     # scan repo only
          python3 Report_Script.py                     # writes run_artifacts/report.html
          chromium-browser --headless --disable-gpu \
            --print-to-pdf=run_artifacts/report.pdf run_artifacts/report.html

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: run_artifacts/*
